### PR TITLE
Enable Work Order Service by default

### PR DESCRIPTION
**Pull request by kaviarasu-ni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/install-systemlink-enterprise/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Enabling the work order service by default as the Landing page shows Test Plans and it should be reachable when clicked on it.

### Why should this Pull Request be merged?

Adds required documentation.

### What testing has been done?

Internal testing.

### CODE REVIEW

**Review by JD-Robertson — COMMENTED** [review]
I would like sign off from TJ before approving this.

**Comment by TJ-G** [comment]
I'm going to ask that @joshuaprewitt and @sudharsan-ni also comment. 

Other than updating the landing page, do we have a good reason to start publicizing the work order service now? Do we have enough functionality in that its a selling point for a customer on the immediate roadmap? If I recall correctly [Deliverable 2642700](https://dev.azure.com/ni/RnD%20Deliverables/_workitems/edit/2642700): Porsche BTS Weissach v1 is the first instance of a customer deliverable that contains any of the work order epics, and has an outlook date of end of C2. Waiting a couple months could save us migration effort - but that's an unknown quantity at this time.

**Comment by sudharsan-ni** [comment]
@TJ-G :) That is the same question I had in the [other PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/701241#1714112027) too. 

One of the reasons why we made this service, an optional installation was that the complete sellable workflow wasn't ready in 2024-02 (creation from template, remote execution) and we also wanted to enable the workflow to create and manage test plans under a product (this workflow is shipping this release). I don't see any upcoming breaking changes from the epics Sharingans are working on. So, no concerns from me, unless we expect migration as part of remote execution support.

A simple alternate fix for landing page bug could be to provide navigation to an app that installs by default. 

image

@joshuaprewitt

**Comment by JD-Robertson** [comment]
> A simple alternate fix for landing page bug could be to provide navigation to an app that installs by default.

There may be breaking changes required to support custom test plan state machines. We can solve those issues without customer impact but there is a cost to doing so. We're okay either way but I wanted to double check here.

**Review by joshuaprewitt — APPROVED** [review]

**Comment by joshuaprewitt** [comment]
> @TJ-G :) That is the same question I had in the [other PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/701241#1714112027) too.
> 
> One of the reasons why we made this service, an optional installation was that the complete sellable workflow wasn't ready in 2024-02 (creation from template, remote execution) and we also wanted to enable the workflow to create and manage test plans under a product (this workflow is shipping this release). I don't see any upcoming breaking changes from the epics Sharingans are working on. So, no concerns from me, unless we expect migration as part of remote execution support.
> 
> A simple alternate fix for landing page bug could be to provide navigation to an app that installs by default.
> 
> image
> 
> @joshuaprewitt

I would prefer to keep Test Plans on the home page if possible. At this point, Test Plans should be treated just like any other released service. If we make a breaking change beyond the April release, we should evaluate the impact and, if we think it is going to be an issue, include the necessary migration support. We are more or less at this point with our internal servers, and we have developed serveral demos for NI Connect and other customer demos.

**Comment by joshuaprewitt** [comment]
> I'm going to ask that @joshuaprewitt and @sudharsan-ni also comment.
> 
> Other than updating the landing page, do we have a good reason to start publicizing the work order service now? Do we have enough functionality in that its a selling point for a customer on the immediate roadmap? If I recall correctly [Deliverable 2642700](https://dev.azure.com/ni/RnD%20Deliverables/_workitems/edit/2642700): Porsche BTS Weissach v1 is the first instance of a customer deliverable that contains any of the work order epics, and has an outlook date of end of C2. Waiting a couple months could save us migration effort - but that's an unknown quantity at this time.

Starting with the April release we think we have enough to sell, especially for the non-BLS customers who we don't think will leverage the remote deployment support up front.

**Review by TJ-G — APPROVED** [review]

**Review by JD-Robertson — APPROVED** [review]

**Comment by TJ-G** [comment]
https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/701241

there is still ongoing discussion in AzDO in the link above

**Review by TJ-G — APPROVED** [review]

**Review by adamarnesen — APPROVED** [review]
Can we add to the comments that this should be set to false when deploying to customer environments unless the customer has purchased, or is piloting, the Test Plans Module?

**Comment by JD-Robertson** [comment]
> Can we add to the comments that this should be set to false when deploying to customer environments unless the customer has purchased, or is piloting, the Test Plans Module?

This file is for customer-facing deployments. If we want this to be opt-in then we shouldn't be changing the default.

**Pull request merged**
